#!/bin/bash
#cd /home/ec2-user/javaapp
#wget https://s3.amazonaws.com/dhqs-mirror-iad/apache-tomcat-8.0.39.tar.gz
#mkdir /opt/tomcat
#tar xvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
#cd /opt/tomcat
#sed -i 's|port="8080"|port="80"|g' conf/server.xml

#############################################################
##Instalar Git
#yum -y install git
############################################################333
##Instalar java
#cd /opt/
#wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz"
#tar xzf jdk-8u144-linux-x64.tar.gz
############################################################3
##Instalar Maven
#wget http://www-us.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
#tar xzf apache-maven-3.5.0-bin.tar.gz -C /opt/apache-maven-3.5.0
#################################################

##Instalar apache tomcat
#wget http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.20/bin/apache-tomcat-8.5.20.tar.gz
#mkdir /opt/tomcat
#tar xvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
#cd /opt/tomcat

#Instalar apache tomcat
#wget http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.20/bin/apache-tomcat-8.5.20.tar.gz
#mkdir /opt/tomcat
#tar xvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
#cd /opt/tomcat

export JAVA_HOME=/opt/jdk1.8.0_144
export JRE_HOME=/opt/jdk1.8.0_144/jre
export PATH=$PATH:/opt/jdk1.8.0_144/bin:/opt/jdk1.8.0_144/jre/bin
export PATH=/opt/apache-maven-3.5.0/bin:$PATH

cd /home/ec2-user/javaapp/

##Descomentar la primera vez
#git clone https://erick.damian-at-405522164029:mmvr8LiuyF7WCw9GujrFs96absmOHTLQqOVzqiBYPbA=@git-codecommit.us-east-1.amazonaws.com/v1/repos/maccess-core
cd dbutil
git pull origin
mvn clean compile
mvn package
mvn install
mv target/dbutil-ds.jar /opt/tomcat/lib/

cd ..
wget http://central.maven.org/maven2/mysql/mysql-connector-java/6.0.3/mysql-connector-java-6.0.3.jar
cp mysql-connector-java-6.0.3.jar /opt/tomcat/lib/

cd maccess-core
git pull origin
mvn clean compile
mvn package
rm -rf /opt/tomcat/webapps/ROOT.war
rm -rf /opt/tomcat/webapps/ROOT
mv target/ROOT.war /opt/tomcat/webapps/




